### ISSUE TITLE
Controlling Lens blur

### ISSUE THREAD

**Issue by harisreedhar** [NatLee/Blur-Generator#1]
Is it possible to control lens blur with a depth map?

**Comment by NatLee** [comment]
Do you mean a feature can process the input image with a depth map into a blur image?

**Comment by harisreedhar** [comment]
> 

Yes. For example depth map generated using [MIDAS](https://github.com/isl-org/MiDaS) to control blur intensity.

**Comment by NatLee** [comment]
It sounds like we need a new filter for generating blur on images.
Here I found a [repo](https://github.com/bransorem/depth-varied-filters) that use depth map to mix and control blur with original input image.
Maybe I can embed it into this tool after discussing with its author.

**Comment by harisreedhar** [comment]
Hi thanks for the repo. It worked with gaussian_blur. For some reason lens_blur not working it outputs black image, may be i did something wrong.

````python
import os
import sys
import cv2
import numpy as np
from blurgenerator import lens_blur, gaussian_blur

def map_range(value, inMin, inMax, outMin, outMax):
    return outMin + (((value - inMin) / (inMax - inMin)) * (outMax - outMin))

def blur_with_depth(img, depth, num_layers=10, min_blur=1, max_blur=100):
    min_depth = np.min(np.unique(depth))
    max_depth = np.max(np.unique(depth))
    step = (max_depth - min_depth) // num_layers
    layers = np.array(range(min_depth, max_depth, step))
    out = np.zeros(img.shape)
    
    for i, value in enumerate(layers):
        dm = cv2.cvtColor(depth, cv2.COLOR_BGR2GRAY)
        m = np.zeros(dm.shape)
        m[dm > value] = 255
        m[dm > (value + step)] = 0
        
        l_mask = depth.copy()
        l_mask[:,:,0] = m[:,:]
        l_mask[:,:,1] = m[:,:]
        l_mask[:,:,2] = m[:,:]
        
        blur_amount = int(map_range(value, 0, 255, min_blur, max_blur))
        slice = gaussian_blur(img, blur_amount)
        #slice = lens_blur(img, radius=blur_amount)
        
        _, mask = cv2.threshold(l_mask, 100, 255, cv2.THRESH_BINARY)
        mask_inv = cv2.bitwise_not(mask)
        layer = cv2.bitwise_and(slice, slice, mask = mask[:,:,0])
        out = cv2.add(out, layer, dtype=0)
    
    h,w,c = out.shape
    ha = h*2 // 3
    wa = w*2 // 3
    out = cv2.resize(out, (wa,ha))

img = cv2.imread("input.jpg")
depth = cv2.imread("depth.png")
output = blur_with_depth(img, depth, num_layers=20, min_blur=1, max_blur=50) 
cv2.imwrite('output.jpg', output)
````

**Comment by NatLee** [comment]
Hi thank you for writing this script.
Can you share 1 pair of example images for testing?

**Comment by harisreedhar** [comment]
I tested with these images:
![depth](https://user-images.githubusercontent.com/46858047/214313200-4f459e5c-1683-418c-b40b-c6a0725271a9.png)
![input](https://user-images.githubusercontent.com/46858047/214313215-de553c13-909c-4fa8-aa51-a856c12cd79e.jpg)

**Comment by NatLee** [comment]
> Hi thanks for the repo. It worked with gaussian_blur. For some reason lens_blur not working it outputs black image, may be i did something wrong.

I tried the script and found that output was actually not black.

Cause the lens blur did preprocessing made `img` get be normalized from 255 to 1.

`output *= 255` will get this below:

<img width="1020" alt="image" src="https://user-images.githubusercontent.com/10178964/215716184-77ecbc88-7de9-43c3-9de1-82c9cf5a71b9.png">

And when using script here:

```python

import numpy as np
import cv2

from blurgenerator import lens_blur, gaussian_blur

def map_range(value, inMin, inMax, outMin, outMax):
    return outMin + (((value - inMin) / (inMax - inMin)) * (outMax - outMin))

def blur_with_depth(img, depth, num_layers=10, min_blur=1, max_blur=100):
    min_depth = np.min(np.unique(depth))
    max_depth = np.max(np.unique(depth))
    step = (max_depth - min_depth) // num_layers
    layers = np.array(range(min_depth, max_depth, step))
    out = np.zeros(img.shape)

    for idx, value in enumerate(layers):
        dm = cv2.cvtColor(depth, cv2.COLOR_BGR2GRAY)
        m = np.zeros(dm.shape)
        m[dm > value] = 255
        m[dm > (value + step)] = 0

        l_mask = depth.copy()
        l_mask[:,:,0] = m[:,:]
        l_mask[:,:,1] = m[:,:]
        l_mask[:,:,2] = m[:,:]

        blur_amount = int(map_range(value, 0, 255, min_blur, max_blur))
        #slice = gaussian_blur(img, blur_amount)
        slice = lens_blur(img/255., radius=blur_amount)

        _, mask = cv2.threshold(l_mask, 100, 255, cv2.THRESH_BINARY)
        mask_inv = cv2.bitwise_not(mask)
        layer = cv2.bitwise_and(slice, slice, mask = mask[:,:,0])
        out = cv2.add(out, layer, dtype=0)

    h,w,c = out.shape
    ha = h*2 // 3
    wa = w*2 // 3
    out = cv2.resize(out, (wa,ha))
    return out

img = cv2.imread("input.jpg")
depth = cv2.imread("depth.png")
output = blur_with_depth(img, depth, num_layers=2, min_blur=1, max_blur=50)
cv2.imwrite('output.jpg', output)
```

We'll generate blur on original image.

<img width="1088" alt="image" src="https://user-images.githubusercontent.com/10178964/215723794-13060a62-d358-4575-a0a4-fcb0621a7eff.png">

But the speed generating blur is very slowly.

I think the method of lens blur need to be optimized. -> https://github.com/NatLee/Blur-Generator/blob/main/src/blurgenerator/lens_blur.py#L118

Thank you for the script and images.

**Comment by harisreedhar** [comment]
So normalizing will solve that issue thanks.
You can improve lens blur speed quite a bit by using ``cv2.filter2D`` instead of ``scipy.signal.convolve2d``. See [gimp lens blur](https://github.com/Davide-sd/GIMP-lens-blur/blob/master/GIMP-lens-blur.py) for reference.

**Comment by NatLee** [comment]
Okay, let me check it

**Comment by NatLee** [comment]
@harisreedhar I have already added this feature in the lastest release version. Please check it.
Thank you for your ideas. 😊
